# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0003_auto_20160508_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='icon',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
