# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0004_auto_20160508_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('is_image', models.BooleanField(default=False)),
                ('url', models.URLField()),
                ('height', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('proxy_url', models.URLField()),
                ('name', models.CharField(max_length=255)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discord.Message')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='guild',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discord.Game'),
        ),
    ]
